// SPDX-License-Identifier: Apache-2.0

//! JSON schema — `serde_json` round-trip with a full JSON-Schema document in `schema_data`.
//!
//! Mirrors `org.apache.pulsar.client.impl.schema.JSONSchema`. The Java client embeds the full
//! JSON-Schema document (generated by Jackson's `JsonSchemaGenerator`) in `schema_data` so the
//! broker can validate the payload structure and de-duplicate compatible schemas across producers.
//!
//! Magnetar derives the schema document at runtime from `T`'s [`schemars::JsonSchema`] impl. The
//! schema document is compact-serialised (no whitespace, stable key ordering) for byte-identical
//! reproducibility across processes — a prerequisite for broker-side schema registry
//! de-duplication.

use std::marker::PhantomData;

use bytes::Bytes;
use schemars::JsonSchema as SchemarsJsonSchema;
use serde::Serialize;
use serde::de::DeserializeOwned;

use super::{Schema, SchemaError};
use crate::pb;

/// Schema that encodes `T` as JSON using `serde_json` and advertises a full JSON-Schema document
/// (derived from `T`'s [`schemars::JsonSchema`] impl) as `schema_data`.
///
/// The schema document is precomputed in [`JsonSchema::new`] to keep [`Schema::schema_data`]
/// hot-path-free; cloning the returned [`Bytes`] is O(1) refcount.
pub struct JsonSchema<T> {
    schema_bytes: Bytes,
    _marker: PhantomData<fn() -> T>,
}

impl<T> Default for JsonSchema<T>
where
    T: SchemarsJsonSchema,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<T> JsonSchema<T>
where
    T: SchemarsJsonSchema,
{
    /// Construct a new [`JsonSchema`], precomputing the JSON-Schema document for `T`.
    ///
    /// # Panics
    ///
    /// Never panics in practice: `serde_json::to_vec` on a `schemars::Schema` only fails on
    /// non-string map keys or non-finite floats, neither of which `schemars` ever emits. If
    /// serialisation does fail we fall back to the empty document `{}` so the schema remains
    /// usable for producer/consumer wiring.
    #[must_use]
    pub fn new() -> Self {
        let schema = schemars::schema_for!(T);
        let schema_bytes = serde_json::to_vec(&schema)
            .map(Bytes::from)
            .unwrap_or_else(|_| Bytes::from_static(b"{}"));
        Self {
            schema_bytes,
            _marker: PhantomData,
        }
    }
}

impl<T> std::fmt::Debug for JsonSchema<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("JsonSchema")
            .field("type", &std::any::type_name::<T>())
            .field("schema_bytes_len", &self.schema_bytes.len())
            .finish_non_exhaustive()
    }
}

impl<T> Schema for JsonSchema<T>
where
    T: Serialize + DeserializeOwned + SchemarsJsonSchema + Send + 'static,
{
    type Owned = T;

    fn schema_type(&self) -> pb::schema::Type {
        pb::schema::Type::Json
    }

    fn schema_data(&self) -> Bytes {
        self.schema_bytes.clone()
    }

    fn encode(&self, value: &Self::Owned) -> Result<Bytes, SchemaError> {
        serde_json::to_vec(value)
            .map(Bytes::from)
            .map_err(|err| SchemaError::Encoding(err.to_string()))
    }

    fn decode(&self, bytes: &[u8]) -> Result<Self::Owned, SchemaError> {
        serde_json::from_slice::<T>(bytes).map_err(|err| SchemaError::Decoding(err.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use schemars::JsonSchema as SchemarsJsonSchema;
    use serde::{Deserialize, Serialize};

    use super::*;

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, SchemarsJsonSchema)]
    struct Person {
        name: String,
        age: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, SchemarsJsonSchema)]
    struct Foo {
        name: String,
        count: i32,
    }

    #[test]
    fn roundtrip() {
        let schema = JsonSchema::<Person>::new();
        let value = Person {
            name: "Ada Lovelace".to_owned(),
            age: 36,
        };
        let encoded = schema.encode(&value).unwrap();
        let decoded = schema.decode(&encoded).unwrap();
        assert_eq!(decoded, value);
    }

    #[test]
    fn schema_data_is_a_full_json_schema_document() {
        let schema = JsonSchema::<Foo>::new();
        let raw = schema.schema_data();
        let value: serde_json::Value =
            serde_json::from_slice(&raw).expect("schema_data must be valid JSON");

        // schemars emits a top-level object whose `properties` describe each field.
        let properties = value
            .get("properties")
            .expect("schema document must carry a `properties` object");
        assert!(
            properties.get("name").is_some(),
            "expected `name` property in schema; got {properties}"
        );
        assert!(
            properties.get("count").is_some(),
            "expected `count` property in schema; got {properties}"
        );

        // `name` is a string, `count` is an integer.
        assert_eq!(
            properties
                .get("name")
                .and_then(|v| v.get("type"))
                .and_then(serde_json::Value::as_str),
            Some("string"),
            "`name` should have JSON type \"string\"; full schema: {value}"
        );
        assert_eq!(
            properties
                .get("count")
                .and_then(|v| v.get("type"))
                .and_then(serde_json::Value::as_str),
            Some("integer"),
            "`count` should have JSON type \"integer\"; full schema: {value}"
        );

        assert_eq!(schema.schema_type(), pb::schema::Type::Json);
    }

    #[test]
    fn schema_data_is_stable_across_constructions() {
        // Byte-identical reproducibility is a precondition for broker-side de-duplication;
        // re-creating a schema for the same `T` must yield the exact same bytes.
        let a = JsonSchema::<Person>::new().schema_data();
        let b = JsonSchema::<Person>::new().schema_data();
        assert_eq!(a, b);
    }

    #[test]
    fn invalid_json_rejected() {
        let schema = JsonSchema::<Person>::new();
        let err = schema.decode(b"{not json}").unwrap_err();
        assert!(matches!(err, SchemaError::Decoding(_)));
    }

    #[test]
    fn unknown_field_in_payload_is_accepted() {
        // serde_json accepts unknown fields by default — this documents the
        // status quo so a future migration to `deny_unknown_fields` is an
        // explicit change, not a silent one.
        let schema = JsonSchema::<Person>::new();
        let payload = br#"{"name":"Bob","age":42,"extra":"ignored"}"#;
        let decoded = schema.decode(payload).unwrap();
        assert_eq!(decoded.name, "Bob");
        assert_eq!(decoded.age, 42);
    }

    #[test]
    fn missing_required_field_rejected() {
        let schema = JsonSchema::<Person>::new();
        let payload = br#"{"name":"Bob"}"#; // missing `age`
        let err = schema.decode(payload).unwrap_err();
        assert!(matches!(err, SchemaError::Decoding(_)));
    }

    #[test]
    fn wrong_type_for_field_rejected() {
        let schema = JsonSchema::<Person>::new();
        let payload = br#"{"name":"Bob","age":"forty-two"}"#;
        let err = schema.decode(payload).unwrap_err();
        assert!(matches!(err, SchemaError::Decoding(_)));
    }

    #[test]
    fn empty_payload_rejected() {
        let schema = JsonSchema::<Person>::new();
        let err = schema.decode(b"").unwrap_err();
        assert!(matches!(err, SchemaError::Decoding(_)));
    }

    #[test]
    fn unicode_in_field_value_round_trips() {
        let schema = JsonSchema::<Person>::new();
        let value = Person {
            name: "Élise · μ".to_owned(),
            age: 30,
        };
        let encoded = schema.encode(&value).unwrap();
        let decoded = schema.decode(&encoded).unwrap();
        assert_eq!(decoded, value);
    }
}
